### PR TITLE
Added missing main heading

### PR DESCRIPTION
**Pull request by stineknutsen**
Added the missing main heading "MMF Culture and Arts Festival" to the news-post page
Styled to look like the desktop design

### CODE REVIEW

**Comment by T0nj3** [comment]
@stineknutsen  Could you resolve these conflicts?

**Comment by stineknutsen** [comment]
Conflicts have been resolved

**Comment by T0nj3** [comment]
Remove the double text "MMF Culture and Arts Festival" before merging!

**Comment by stineknutsen** [comment]
Removed the double text

**Review by T0nj3 — APPROVED** [review]

**Pull request merged**
