### PR TITLE
Update font and size

### PR DESCRIPTION
**Pull request by EVeskje**
Update font and size on the Upcoming Events.
Also changed the JS calendar to fix the dates.

### CODE REVIEW

**Review by IlyaAdlan — APPROVED** [review]
Font and size is updated, and looks good to go

**Comment by IlyaAdlan** [comment]
EVeskje, could you look at the conflict on this branch and try to solve it? Need it so  i can merge it to main

**Comment by EVeskje** [comment]
> EVeskje, could you look at the conflict on this branch and try to solve it? Need it so i can merge it to main

Yes, I will try to solve it :)

**Comment by EVeskje** [comment]
> EVeskje, could you look at the conflict on this branch and try to solve it? Need it so i can merge it to main

Does it looks good now?

**Comment by IlyaAdlan** [comment]
Now it looks good, Thanks

**Comment by T0nj3** [comment]
Hey, @IlyaAdlan this PR had issues with the calendar on index, i'll revert it!

**Pull request merged**
