### PR TITLE
Created event.html, section 1

### PR DESCRIPTION
**Pull request by vicwinsj**
- [ ] Created event.html
- [ ] Added HTML and CSS according to design

### CODE REVIEW

**Comment by EliNygard** [comment]
There is a conflict regarding the head title and description. In this PR it says head title = News. In main head title = Blog. What is correct? I assume Blog since news.html already exists, but I want to double check with you before I merge :)

**Review by EliNygard — COMMENTED** [review]
There is a conflict regarding the head title and description. In this PR it says head title = News. In the main branch head title = Blog. What is correct? I assume Blog since news.html already exists, but I want to double check with you before I merge :)

**Comment by benjaminskarding** [comment]
> There is a conflict regarding the head title and description. In this PR it says head title = News. In the main branch head title = Blog. What is correct? I assume Blog since news.html already exists, but I want to double check with you before I merge :)

Event is a separate page, there's been some drastic changes with blog pages being discarded and merged into News, hence the confusion. Should be cleaned up by the end of the day

Title here should be Event

**Comment by vicwinsj** [comment]
> There is a conflict regarding the head title and description. In this PR it says head title = News. In the main branch head title = Blog. What is correct? I assume Blog since news.html already exists, but I want to double check with you before I merge :)

My bad, I was a bit quick when making the page, I forgot to update both title and meta description.

**Review by EliNygard — COMMENTED** [review]
To resolve the conflict I copied the new code and pasted it. That's why it looks chaotic in here. Should be correct now.

**Review by EliNygard — APPROVED** [review]
Looks good now. Thank you!

**Review by EliNygard — APPROVED** [review]
Perfect :D

**Pull request merged**
