### PR TITLE
Moved relevant code to new pages and deleted old (not in use) pages.

### PR DESCRIPTION
**Pull request by benjaminskarding**

### CODE REVIEW

**Comment by benjaminskarding** [comment]
I see we've got one of our guys working on updated code for section 3 of this page. (This version is off-center)

Might have to cross-check the two.

Rest should be ok.

**Review by X7-C — APPROVED** [review]
Looks right, Couldnt compare though from Blog Post

**Comment by X7-C** [comment]
Forgot to add comment through the deploy previews it looked correct. :)

**Comment by benjaminskarding** [comment]
Is everything approved here? Has it been commited to main or should i do something?

**Review by lem31 — APPROVED** [review]

**Comment by X7-C** [comment]
Experiencing an issue with the branch having a conflict within "pages/blog-post.html" Yet the file has been deleted from this branch? 
image_2024-04-05_122155902
)

**Pull request closed without merging**
