### PR TITLE
209 tailwind resizing test !! IMPORTANT TO READ !!

### PR DESCRIPTION
**Pull request by LauraBLei**
So here i have created a new styles.css that the QA team will be using. Both Styles.css and output.css is added to gitIgnore, so that less files will be committed each time we make a pull request. 

the output.css file - is the file that we will use when building the pages (you will not be looking at this) 

the styles.css file - is the minimized file of the output.css file - this you can run by writing the following in the terminal: npm run build

BUT! in general do not look to much into the files. we do not write ourselves in that document. we only write in the input.css files or the html file, this is what matters. 

What i have done now is half the size of the file itself - this is what most pages and tailwind itself recommend doing. 
If you have any questions feel free to ask - or any other suggestions. 

- I am looking into purge!! and it will come, i just need to look at it a bit more

### CODE REVIEW

**Comment by EliNygard** [comment]
Hi Laura! Thank you for your comment. On every PR we get the branch has a conflict with the styles.css file. As does this PR. We therefore have to look at it an resolve the conflict to be able to review and merge the PR. I am not sure why there is a conflict in the file. I don't have a suggestion or solution. I just wanted to let you know. Maybe you know of it already. Our SM is aware and will inform your team's SM.

**Comment by LauraBLei** [comment]
This should fix that problem! since the files wont be coming with the PR! :))

**Comment by EliNygard** [comment]
I see :) That would be nice. Right now we are not able to resolve the conflict, so I can't approve it...

**Comment by LauraBLei** [comment]
i see! we might need to start a bit from scratch then, i will speak to my team about it, but if you find a solution lmk!

**Comment by EliNygard** [comment]
Skjermbilde 2024-03-22 132706

Whisperpiano and I tried doing this in the terminal, but we could not figure it out. Unfortunately :) Do you understand something of it, Laura? Do you have access to try to resolve the conflict?

**Comment by EliNygard** [comment]
I spoke with my team. They are okay with your plan to create a new big PR with the old PRs and the css fix :) our team are available on Monday and Tuesday next week to review. Let me know if you have any questions! I am available for comments here and chat if you need to.

**Comment by LauraBLei** [comment]
nice! i will speak with my team again, and be on it this weekend so its ready monday! :))

**Pull request closed without merging**
