### PR TITLE
322 add and update footer to all pages

### PR DESCRIPTION
**Pull request by Iseost**
Did update the design and added footer to available pages.
Did also add links (missing instagram and facebook.)

### CODE REVIEW

**Comment by EliNygard** [comment]
Hi, the code looks very good but I have some comments unfortunately :)  

- This PR has lots of conflicts. So many I can not easily fix them. I think it would be less complicated to fix this on your side. I can easily make mistakes if I have to resolve conflicts on all the pages in the project. This PR still has the children page which was deleted due to privacy issues.
Skjermbilde 2024-04-10 090850

- This PR is very big. Over 2500 new lines of code and 1000 removed. This makes it difficult to have full control over the quality assurance of the PR. I know now I should have mentioned this on the PR we closed, so you knew this before creating this new one. But this PR is also big because links where also added. The smaller a PR is the better quality assurance we can give.  
Skjermbilde 2024-04-10 091338

Remember this is a learning experience :) no critic! I learn from this too!

I could have reviewed this PR even though it is so big, but because of all the conflicts I am not able. I can mess it up. The best practice to keep the PR small and transparent is to create one PR for each page you add the footer to, and only the footer. Then a separate PR for the links and svgs. I know this creates more work for you, I'm sorry.

**Review by EliNygard — CHANGES_REQUESTED** [review]
I wrote some comments. Lets figure out what we can do

**Comment by annechh** [comment]
Will it be better for you if we create a issue per page to add the footer ? =)

**Comment by annechh** [comment]
Then we do that, so we can close this one and we will make new issues for each page =D

**Comment by EliNygard** [comment]
I am closing this and wait for new PRs focusing on each page

**Pull request closed without merging**
