### PR TITLE
Footer path corrections and adding logo link

### PR DESCRIPTION
**Pull request by Inaelise**
- [x] Correct paths (../)
- [x] Add link on logo to index.html

### CODE REVIEW

**Review by X7-C — COMMENTED** [review]
Im seeing an issue that is occuring in here in 
image
These lines. 
Other then that I am seeing less the code seems to work. So before approving I am just questioning

**Comment by Inaelise** [comment]
The issue was a missing closing tag. It should be fixed now :)

**Comment by Inaelise** [comment]
That's strange, it works for me

**Review by X7-C — APPROVED** [review]
Managed to fix the issue on my end :) It works.

**Pull request merged**
