### PR TITLE
141 implement responsiveness   header

### PR DESCRIPTION
**Pull request by anneloviseramstad**
Added responsiveness to header/navigationbar using tailwind. Made js-file with function for hamburger-menu on sm/md screen.

### CODE REVIEW

**Review by IlyaAdlan — COMMENTED** [review]
404.html does not have an responsive header, not sure if this is how its suppoused to look like.

**Comment by T0nj3** [comment]
We need to resolve these conflicts. I took a quick look at it but i can't figure it out as it is a lot of them.

**Comment by T0nj3** [comment]
@Johanf92 @IlyaAdlan The conflicts has been resolved, could you go through it? :)

**Comment by T0nj3** [comment]
@anneloviseramstad  Could you go trough these conflicts and solve them? :)

**Comment by cnnrbrn** [comment]
The prettier config file is good, has the correct settings, but the PR should only contain the config file, not any other formatted files.

**Review by IlyaAdlan — APPROVED** [review]

**Comment by anneloviseramstad** [comment]
Looking into it

**Pull request closed without merging**
