### PR TITLE
Created and added Header to all current pages

### PR DESCRIPTION
**Pull request by benjaminskarding**
- [x] Moved "colors" to the extend module in tailwind cfg file. It was overwriting the default colors when placed directly under "theme", making all the default colors inaccessible.

- [x] Added "sans" keyword to fontfamily module's main font. 
- This keyword makes the browser default to that font. This way we don't have to define the default font everywhere.

- [x] Changed the padding settings for the alt-button component
- Done in order to center the text vertically. It was slightly offset when using same padding on top and bottom for some reason.

- [x] Added two custom css classes in input.css
- The first is for animating the language options.
- The second for hiding an ugly browser default styling for cancelling user input (in search fields for example).

- [x] Created HTML for header and a search drawer that will be triggered using js. 
- It was neccessary to have the search-drawer code outside the header tag.

- [x] Added header code to all available html pages.

### CODE REVIEW

**Review by Whisperpiano — CHANGES_REQUESTED** [review]
Looking good! :)

Can you move back colors to theme as we talked before please? Remember that you can add always more shades if needed later, and as much as colors as you are going to use: 

image

**Review by Whisperpiano — APPROVED** [review]

**Comment by EliNygard** [comment]
The header looks really nice. A few adjustments: 

- [ ] all img elements must have an alt attribute with text
- [ ] Line 57 in the code, section with the id="search-drawer-from-header": Section lacks heading. Consider using a div element or another element instead. 
- [ ] Line 57 in the code, section with the id="search-drawer-from-header": try using aria-label instead of aria-labelledby. I get an error now because aria-labelledby must point to an element in the same document
- [ ] Line 60 in the code, form: Add a label tag to the form. It's recommended for accessibility and usability purposes. You can visually hide it for design purposes, but then it will still be available for screen readers.

**Review by EliNygard — CHANGES_REQUESTED** [review]
The header looks really nice. A few adjustments:

- [ ] all img elements must have an alt attribute with text 

- [ ] Line 57 in the code, section with the id="search-drawer-from-header": Section lacks heading. Consider using a div element or another element instead.

- [ ]  Line 57 in the code, section with the id="search-drawer-from-header": try using aria-label instead of aria-labelledby. I get an error now because aria-labelledby must point to an element in the same document

- [ ] Line 60 in the code, form: Add a label tag to the form. It's recommended for accessibility and usability purposes. You can visually hide it for design purposes, but then it will still be available for screen readers.

**Comment by benjaminskarding** [comment]
- [ ] Added alt-attributes to all images

- [ ] Created <h2> element for better semantic structuring and screen reader navigation.

- [ ] Changed aria-labelledyby attribute of the search section to "search-bar" for clearer screen reader identification.

- [ ] Added a <label> tag on line 62 for the search input field to improve form accessibility, while keeping it visually hidden.

**Comment by benjaminskarding** [comment]
Should be added to all pages now

**Review by EliNygard — APPROVED** [review]
Thank you! :)

**Pull request merged**
